// Generated from bingo_messages.proto by scripts/generate-protobuf-types.js.
// Do not edit this file directly.
import type { BingoMode, BingoRoomStatus } from './messages';

type MessageValues<T> = { [K in keyof T as T[K] extends Function ? never : K]: T[K] };

export class AuthenticatePlayerReq {
  accessToken!: string;

  constructor(values: MessageValues<AuthenticatePlayerReq>) {
    Object.assign(this, values);
  }
}

export class AuthenticatePlayerRes {
  accepted!: boolean;
  actorId!: string | null;
  displayName!: string | null;
  reason!: string | null;

  constructor(values: MessageValues<AuthenticatePlayerRes>) {
    Object.assign(this, values);
  }
}

export class AuthenticateReq {
  accessToken!: string;

  constructor(values: MessageValues<AuthenticateReq>) {
    Object.assign(this, values);
  }
}

export class AuthenticateRes {
  actorId!: string;
  displayName!: string;

  constructor(values: MessageValues<AuthenticateRes>) {
    Object.assign(this, values);
  }
}

export class BingoGameEndedNotify {
  state!: BingoRoomState;

  constructor(values: MessageValues<BingoGameEndedNotify>) {
    Object.assign(this, values);
  }
}

export class BingoGameStartedNotify {
  state!: BingoRoomState;

  constructor(values: MessageValues<BingoGameStartedNotify>) {
    Object.assign(this, values);
  }
}

export class BingoNumberDrawnNotify {
  roomId!: string;
  drawSeq!: number;
  number!: number;
  state!: BingoRoomState;

  constructor(values: MessageValues<BingoNumberDrawnNotify>) {
    Object.assign(this, values);
  }
}

export class BingoPayloadEnvelope {
  type!: string;
  payload!: Uint8Array;

  constructor(values: MessageValues<BingoPayloadEnvelope>) {
    Object.assign(this, values);
  }
}

export class BingoPlayerState {
  actorId!: string;
  displayName!: string;
  seat!: number;
  isHost!: boolean;
  card!: number[];
  marks!: boolean[];
  completedLines!: number;
  wins!: number;
  losses!: number;

  constructor(values: MessageValues<BingoPlayerState>) {
    Object.assign(this, values);
  }
}

export class BingoRewardAcquiredEvent {
  roomId!: string;
  actorId!: string;
  drawSeq!: number;
  itemId!: string;
  itemName!: string;
  rarity!: string;

  constructor(values: MessageValues<BingoRewardAcquiredEvent>) {
    Object.assign(this, values);
  }
}

export class BingoRewardAnnouncedNotify {
  roomId!: string;
  actorId!: string;
  drawSeq!: number;
  itemId!: string;
  itemName!: string;
  rarity!: string;

  constructor(values: MessageValues<BingoRewardAnnouncedNotify>) {
    Object.assign(this, values);
  }
}

export class BingoRoomCreateReq {
  settings!: BingoRoomSettingsPayload;

  constructor(values: MessageValues<BingoRoomCreateReq>) {
    Object.assign(this, values);
  }
}

export class BingoRoomJoinReq {
  roomId!: string;
  actorId!: string;
  displayName!: string;
  observeOnly!: boolean;

  constructor(values: MessageValues<BingoRoomJoinReq>) {
    Object.assign(this, values);
  }
}

export class BingoRoomJoinRes {
  state!: BingoRoomState;

  constructor(values: MessageValues<BingoRoomJoinRes>) {
    Object.assign(this, values);
  }
}

export class BingoRoomSettingsPayload {
  roomName!: string;
  mode!: BingoMode;
  requiredPlayers!: number;
  maxDrawNumber!: number;
  purpose!: string;
  observedRoomId!: string | null;

  constructor(values: MessageValues<BingoRoomSettingsPayload>) {
    Object.assign(this, values);
  }
}

export class BingoRoomState {
  roomId!: string;
  status!: BingoRoomStatus;
  hostActorId!: string;
  canStart!: boolean;
  drawSeq!: number;
  lastDrawnNumber!: number | null;
  drawnNumbers!: number[];
  players!: BingoPlayerState[];
  winners!: string[];

  constructor(values: MessageValues<BingoRoomState>) {
    Object.assign(this, values);
  }
}

export class DeliverBingoGameEndedMsg {
  notification!: BingoGameEndedNotify;

  constructor(values: MessageValues<DeliverBingoGameEndedMsg>) {
    Object.assign(this, values);
  }
}

export class DeliverBingoGameStartedMsg {
  notification!: BingoGameStartedNotify;

  constructor(values: MessageValues<DeliverBingoGameStartedMsg>) {
    Object.assign(this, values);
  }
}

export class DeliverBingoNumberDrawnMsg {
  notification!: BingoNumberDrawnNotify;

  constructor(values: MessageValues<DeliverBingoNumberDrawnMsg>) {
    Object.assign(this, values);
  }
}

export class DeliverBingoRewardAnnouncedMsg {
  notification!: BingoRewardAnnouncedNotify;

  constructor(values: MessageValues<DeliverBingoRewardAnnouncedMsg>) {
    Object.assign(this, values);
  }
}

export class DeliverPlayerJoinedMsg {
  notification!: PlayerJoinedNotify;

  constructor(values: MessageValues<DeliverPlayerJoinedMsg>) {
    Object.assign(this, values);
  }
}

export class DestroyBingoActorMsg {

  constructor(values: MessageValues<DestroyBingoActorMsg>) {
    Object.assign(this, values);
  }
}

export class GetPlayerRecordReq {
  actorId!: string;

  constructor(values: MessageValues<GetPlayerRecordReq>) {
    Object.assign(this, values);
  }
}

export class GetPlayerRecordRes {
  actorId!: string;
  wins!: number;
  losses!: number;

  constructor(values: MessageValues<GetPlayerRecordRes>) {
    Object.assign(this, values);
  }
}

export class LeaveFinishedBingoRoomMsg {

  constructor(values: MessageValues<LeaveFinishedBingoRoomMsg>) {
    Object.assign(this, values);
  }
}

export class MatchBingoApiReq {
  actorId!: string;
  displayName!: string;
  mode!: BingoMode;

  constructor(values: MessageValues<MatchBingoApiReq>) {
    Object.assign(this, values);
  }
}

export class MatchBingoApiRes {
  roomId!: string;

  constructor(values: MessageValues<MatchBingoApiRes>) {
    Object.assign(this, values);
  }
}

export class MatchBingoReq {
  mode!: BingoMode;

  constructor(values: MessageValues<MatchBingoReq>) {
    Object.assign(this, values);
  }
}

export class MatchBingoRes {
  roomId!: string;
  state!: BingoRoomState;

  constructor(values: MessageValues<MatchBingoRes>) {
    Object.assign(this, values);
  }
}

export class ObserveBingoEventsReq {
  roomId!: string;

  constructor(values: MessageValues<ObserveBingoEventsReq>) {
    Object.assign(this, values);
  }
}

export class ObserveBingoEventsRes {
  subscribed!: boolean;

  constructor(values: MessageValues<ObserveBingoEventsRes>) {
    Object.assign(this, values);
  }
}

export class PlayerActorCreateReq {
  actorId!: string;
  displayName!: string;

  constructor(values: MessageValues<PlayerActorCreateReq>) {
    Object.assign(this, values);
  }
}

export class PlayerActorTransferState {
  displayName!: string;
  destroyAfterEntrySpotJoin!: boolean;
  disconnected!: boolean;

  constructor(values: MessageValues<PlayerActorTransferState>) {
    Object.assign(this, values);
  }
}

export class PlayerJoinedNotify {
  roomId!: string;
  actorId!: string;
  displayName!: string;
  seat!: number;
  isHost!: boolean;
  state!: BingoRoomState;

  constructor(values: MessageValues<PlayerJoinedNotify>) {
    Object.assign(this, values);
  }
}

export class ReportBingoResultReq {
  roomId!: string;
  actorId!: string;
  won!: boolean;
  finalDrawSeq!: number;

  constructor(values: MessageValues<ReportBingoResultReq>) {
    Object.assign(this, values);
  }
}

export class ReportBingoResultRes {
  actorId!: string;
  wins!: number;
  losses!: number;

  constructor(values: MessageValues<ReportBingoResultRes>) {
    Object.assign(this, values);
  }
}

export class ReserveBingoRoomReq {
  mode!: BingoMode;
  actorId!: string;
  levelBucket!: string;

  constructor(values: MessageValues<ReserveBingoRoomReq>) {
    Object.assign(this, values);
  }
}

export class ReserveBingoRoomRes {
  roomId!: string;
  settings!: BingoRoomSettingsPayload;

  constructor(values: MessageValues<ReserveBingoRoomRes>) {
    Object.assign(this, values);
  }
}

export class StopObservingBingoEventsReq {
  roomId!: string;

  constructor(values: MessageValues<StopObservingBingoEventsReq>) {
    Object.assign(this, values);
  }
}

export class StopObservingBingoEventsRes {
  stopped!: boolean;

  constructor(values: MessageValues<StopObservingBingoEventsRes>) {
    Object.assign(this, values);
  }
}

export class SubmitBingoCardReq {
  roomId!: string;
  card!: number[];

  constructor(values: MessageValues<SubmitBingoCardReq>) {
    Object.assign(this, values);
  }
}

export class SubmitBingoCardRes {
  state!: BingoRoomState;

  constructor(values: MessageValues<SubmitBingoCardRes>) {
    Object.assign(this, values);
  }
}

export const BingoGeneratedMessageConstructors = {
  AuthenticatePlayerReq,
  AuthenticatePlayerRes,
  AuthenticateReq,
  AuthenticateRes,
  BingoGameEndedNotify,
  BingoGameStartedNotify,
  BingoNumberDrawnNotify,
  BingoPayloadEnvelope,
  BingoPlayerState,
  BingoRewardAcquiredEvent,
  BingoRewardAnnouncedNotify,
  BingoRoomCreateReq,
  BingoRoomJoinReq,
  BingoRoomJoinRes,
  BingoRoomSettingsPayload,
  BingoRoomState,
  DeliverBingoGameEndedMsg,
  DeliverBingoGameStartedMsg,
  DeliverBingoNumberDrawnMsg,
  DeliverBingoRewardAnnouncedMsg,
  DeliverPlayerJoinedMsg,
  DestroyBingoActorMsg,
  GetPlayerRecordReq,
  GetPlayerRecordRes,
  LeaveFinishedBingoRoomMsg,
  MatchBingoApiReq,
  MatchBingoApiRes,
  MatchBingoReq,
  MatchBingoRes,
  ObserveBingoEventsReq,
  ObserveBingoEventsRes,
  PlayerActorCreateReq,
  PlayerActorTransferState,
  PlayerJoinedNotify,
  ReportBingoResultReq,
  ReportBingoResultRes,
  ReserveBingoRoomReq,
  ReserveBingoRoomRes,
  StopObservingBingoEventsReq,
  StopObservingBingoEventsRes,
  SubmitBingoCardReq,
  SubmitBingoCardRes,
} as const;

type BingoFieldDescriptor = {
  readonly number: number;
  readonly name: string;
  readonly kind: string;
  readonly repeated: boolean;
  readonly optional: boolean;
};

const bingoDescriptors: Readonly<Partial<Record<string, readonly BingoFieldDescriptor[]>>> = {
  "AuthenticatePlayerReq": [
    {
      "number": 1,
      "name": "accessToken",
      "kind": "string",
      "repeated": false,
      "optional": false
    }
  ],
  "AuthenticatePlayerRes": [
    {
      "number": 1,
      "name": "accepted",
      "kind": "bool",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "actorId",
      "kind": "string",
      "repeated": false,
      "optional": true
    },
    {
      "number": 3,
      "name": "displayName",
      "kind": "string",
      "repeated": false,
      "optional": true
    },
    {
      "number": 4,
      "name": "reason",
      "kind": "string",
      "repeated": false,
      "optional": true
    }
  ],
  "AuthenticateReq": [
    {
      "number": 1,
      "name": "accessToken",
      "kind": "string",
      "repeated": false,
      "optional": false
    }
  ],
  "AuthenticateRes": [
    {
      "number": 1,
      "name": "actorId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "displayName",
      "kind": "string",
      "repeated": false,
      "optional": false
    }
  ],
  "BingoGameEndedNotify": [
    {
      "number": 1,
      "name": "state",
      "kind": "message:BingoRoomState",
      "repeated": false,
      "optional": false
    }
  ],
  "BingoGameStartedNotify": [
    {
      "number": 1,
      "name": "state",
      "kind": "message:BingoRoomState",
      "repeated": false,
      "optional": false
    }
  ],
  "BingoNumberDrawnNotify": [
    {
      "number": 1,
      "name": "roomId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "drawSeq",
      "kind": "int32",
      "repeated": false,
      "optional": false
    },
    {
      "number": 3,
      "name": "number",
      "kind": "int32",
      "repeated": false,
      "optional": false
    },
    {
      "number": 4,
      "name": "state",
      "kind": "message:BingoRoomState",
      "repeated": false,
      "optional": false
    }
  ],
  "BingoPayloadEnvelope": [
    {
      "number": 1,
      "name": "type",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "payload",
      "kind": "bytes",
      "repeated": false,
      "optional": false
    }
  ],
  "BingoPlayerState": [
    {
      "number": 1,
      "name": "actorId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "displayName",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 3,
      "name": "seat",
      "kind": "int32",
      "repeated": false,
      "optional": false
    },
    {
      "number": 4,
      "name": "isHost",
      "kind": "bool",
      "repeated": false,
      "optional": false
    },
    {
      "number": 5,
      "name": "card",
      "kind": "int32",
      "repeated": true,
      "optional": false
    },
    {
      "number": 6,
      "name": "marks",
      "kind": "bool",
      "repeated": true,
      "optional": false
    },
    {
      "number": 7,
      "name": "completedLines",
      "kind": "int32",
      "repeated": false,
      "optional": false
    },
    {
      "number": 8,
      "name": "wins",
      "kind": "int32",
      "repeated": false,
      "optional": false
    },
    {
      "number": 9,
      "name": "losses",
      "kind": "int32",
      "repeated": false,
      "optional": false
    }
  ],
  "BingoRewardAcquiredEvent": [
    {
      "number": 1,
      "name": "roomId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "actorId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 3,
      "name": "drawSeq",
      "kind": "int32",
      "repeated": false,
      "optional": false
    },
    {
      "number": 4,
      "name": "itemId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 5,
      "name": "itemName",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 6,
      "name": "rarity",
      "kind": "string",
      "repeated": false,
      "optional": false
    }
  ],
  "BingoRewardAnnouncedNotify": [
    {
      "number": 1,
      "name": "roomId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "actorId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 3,
      "name": "drawSeq",
      "kind": "int32",
      "repeated": false,
      "optional": false
    },
    {
      "number": 4,
      "name": "itemId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 5,
      "name": "itemName",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 6,
      "name": "rarity",
      "kind": "string",
      "repeated": false,
      "optional": false
    }
  ],
  "BingoRoomCreateReq": [
    {
      "number": 1,
      "name": "settings",
      "kind": "message:BingoRoomSettingsPayload",
      "repeated": false,
      "optional": false
    }
  ],
  "BingoRoomJoinReq": [
    {
      "number": 1,
      "name": "roomId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "actorId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 3,
      "name": "displayName",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 4,
      "name": "observeOnly",
      "kind": "bool",
      "repeated": false,
      "optional": false
    }
  ],
  "BingoRoomJoinRes": [
    {
      "number": 1,
      "name": "state",
      "kind": "message:BingoRoomState",
      "repeated": false,
      "optional": false
    }
  ],
  "BingoRoomSettingsPayload": [
    {
      "number": 1,
      "name": "roomName",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "mode",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 3,
      "name": "requiredPlayers",
      "kind": "int32",
      "repeated": false,
      "optional": false
    },
    {
      "number": 4,
      "name": "maxDrawNumber",
      "kind": "int32",
      "repeated": false,
      "optional": false
    },
    {
      "number": 5,
      "name": "purpose",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 6,
      "name": "observedRoomId",
      "kind": "string",
      "repeated": false,
      "optional": true
    }
  ],
  "BingoRoomState": [
    {
      "number": 1,
      "name": "roomId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "status",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 3,
      "name": "hostActorId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 4,
      "name": "canStart",
      "kind": "bool",
      "repeated": false,
      "optional": false
    },
    {
      "number": 5,
      "name": "drawSeq",
      "kind": "int32",
      "repeated": false,
      "optional": false
    },
    {
      "number": 6,
      "name": "lastDrawnNumber",
      "kind": "int32",
      "repeated": false,
      "optional": true
    },
    {
      "number": 7,
      "name": "drawnNumbers",
      "kind": "int32",
      "repeated": true,
      "optional": false
    },
    {
      "number": 8,
      "name": "players",
      "kind": "message:BingoPlayerState",
      "repeated": true,
      "optional": false
    },
    {
      "number": 9,
      "name": "winners",
      "kind": "string",
      "repeated": true,
      "optional": false
    }
  ],
  "DeliverBingoGameEndedMsg": [
    {
      "number": 1,
      "name": "notification",
      "kind": "message:BingoGameEndedNotify",
      "repeated": false,
      "optional": false
    }
  ],
  "DeliverBingoGameStartedMsg": [
    {
      "number": 1,
      "name": "notification",
      "kind": "message:BingoGameStartedNotify",
      "repeated": false,
      "optional": false
    }
  ],
  "DeliverBingoNumberDrawnMsg": [
    {
      "number": 1,
      "name": "notification",
      "kind": "message:BingoNumberDrawnNotify",
      "repeated": false,
      "optional": false
    }
  ],
  "DeliverBingoRewardAnnouncedMsg": [
    {
      "number": 1,
      "name": "notification",
      "kind": "message:BingoRewardAnnouncedNotify",
      "repeated": false,
      "optional": false
    }
  ],
  "DeliverPlayerJoinedMsg": [
    {
      "number": 1,
      "name": "notification",
      "kind": "message:PlayerJoinedNotify",
      "repeated": false,
      "optional": false
    }
  ],
  "DestroyBingoActorMsg": [],
  "GetPlayerRecordReq": [
    {
      "number": 1,
      "name": "actorId",
      "kind": "string",
      "repeated": false,
      "optional": false
    }
  ],
  "GetPlayerRecordRes": [
    {
      "number": 1,
      "name": "actorId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "wins",
      "kind": "int32",
      "repeated": false,
      "optional": false
    },
    {
      "number": 3,
      "name": "losses",
      "kind": "int32",
      "repeated": false,
      "optional": false
    }
  ],
  "LeaveFinishedBingoRoomMsg": [],
  "MatchBingoApiReq": [
    {
      "number": 1,
      "name": "actorId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "displayName",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 3,
      "name": "mode",
      "kind": "string",
      "repeated": false,
      "optional": false
    }
  ],
  "MatchBingoApiRes": [
    {
      "number": 1,
      "name": "roomId",
      "kind": "string",
      "repeated": false,
      "optional": false
    }
  ],
  "MatchBingoReq": [
    {
      "number": 1,
      "name": "mode",
      "kind": "string",
      "repeated": false,
      "optional": false
    }
  ],
  "MatchBingoRes": [
    {
      "number": 1,
      "name": "roomId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "state",
      "kind": "message:BingoRoomState",
      "repeated": false,
      "optional": false
    }
  ],
  "ObserveBingoEventsReq": [
    {
      "number": 1,
      "name": "roomId",
      "kind": "string",
      "repeated": false,
      "optional": false
    }
  ],
  "ObserveBingoEventsRes": [
    {
      "number": 1,
      "name": "subscribed",
      "kind": "bool",
      "repeated": false,
      "optional": false
    }
  ],
  "PlayerActorCreateReq": [
    {
      "number": 1,
      "name": "actorId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "displayName",
      "kind": "string",
      "repeated": false,
      "optional": false
    }
  ],
  "PlayerActorTransferState": [
    {
      "number": 1,
      "name": "displayName",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "destroyAfterEntrySpotJoin",
      "kind": "bool",
      "repeated": false,
      "optional": false
    },
    {
      "number": 3,
      "name": "disconnected",
      "kind": "bool",
      "repeated": false,
      "optional": false
    }
  ],
  "PlayerJoinedNotify": [
    {
      "number": 1,
      "name": "roomId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "actorId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 3,
      "name": "displayName",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 4,
      "name": "seat",
      "kind": "int32",
      "repeated": false,
      "optional": false
    },
    {
      "number": 5,
      "name": "isHost",
      "kind": "bool",
      "repeated": false,
      "optional": false
    },
    {
      "number": 6,
      "name": "state",
      "kind": "message:BingoRoomState",
      "repeated": false,
      "optional": false
    }
  ],
  "ReportBingoResultReq": [
    {
      "number": 1,
      "name": "roomId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "actorId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 3,
      "name": "won",
      "kind": "bool",
      "repeated": false,
      "optional": false
    },
    {
      "number": 4,
      "name": "finalDrawSeq",
      "kind": "int32",
      "repeated": false,
      "optional": false
    }
  ],
  "ReportBingoResultRes": [
    {
      "number": 1,
      "name": "actorId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "wins",
      "kind": "int32",
      "repeated": false,
      "optional": false
    },
    {
      "number": 3,
      "name": "losses",
      "kind": "int32",
      "repeated": false,
      "optional": false
    }
  ],
  "ReserveBingoRoomReq": [
    {
      "number": 1,
      "name": "mode",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "actorId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 3,
      "name": "levelBucket",
      "kind": "string",
      "repeated": false,
      "optional": false
    }
  ],
  "ReserveBingoRoomRes": [
    {
      "number": 1,
      "name": "roomId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "settings",
      "kind": "message:BingoRoomSettingsPayload",
      "repeated": false,
      "optional": false
    }
  ],
  "StopObservingBingoEventsReq": [
    {
      "number": 1,
      "name": "roomId",
      "kind": "string",
      "repeated": false,
      "optional": false
    }
  ],
  "StopObservingBingoEventsRes": [
    {
      "number": 1,
      "name": "stopped",
      "kind": "bool",
      "repeated": false,
      "optional": false
    }
  ],
  "SubmitBingoCardReq": [
    {
      "number": 1,
      "name": "roomId",
      "kind": "string",
      "repeated": false,
      "optional": false
    },
    {
      "number": 2,
      "name": "card",
      "kind": "int32",
      "repeated": true,
      "optional": false
    }
  ],
  "SubmitBingoCardRes": [
    {
      "number": 1,
      "name": "state",
      "kind": "message:BingoRoomState",
      "repeated": false,
      "optional": false
    }
  ]
};

const textEncoder = new TextEncoder();
const textDecoder = new TextDecoder();

export const BingoGeneratedProtobufCodec = {
  encode(typeName: string, value: unknown): Uint8Array {
    return encodeMessage(typeName, value as Record<string, unknown>);
  },
  decode(typeName: string, payload: Uint8Array): unknown {
    return decodeMessage(typeName, payload);
  }
};

function encodeMessage(typeName: string, value: Record<string, unknown>): Uint8Array {
  const fields = requireDescriptor(typeName);
  const chunks: Uint8Array[] = [];
  for (const field of fields) {
    const raw = value[field.name];
    if (raw === undefined || raw === null) continue;
    const values = field.repeated ? raw as readonly unknown[] : [raw];
    if (field.repeated && (field.kind === 'int32' || field.kind === 'uint64' || field.kind === 'bool')) {
      if (values.length > 0) {
        const packed = concatBytes(values.map((entry) => encodeScalarVarint(field.kind, entry)));
        chunks.push(encodeKey(field.number, 2), encodeLengthDelimited(packed));
      }
      continue;
    }
    for (const entry of values) {
      if (isDefaultScalar(field.kind, entry)) continue;
      if (field.kind === "int32" || field.kind === "uint64" || field.kind === "bool") {
        chunks.push(encodeKey(field.number, 0), encodeScalarVarint(field.kind, entry));
      } else {
        const bytes = field.kind === "string"
          ? textEncoder.encode(String(entry))
          : field.kind === "bytes"
            ? entry as Uint8Array
            : encodeMessage(field.kind.slice("message:".length), entry as Record<string, unknown>);
        chunks.push(encodeKey(field.number, 2), encodeLengthDelimited(bytes));
      }
    }
  }
  return concatBytes(chunks);
}

function decodeMessage(typeName: string, payload: Uint8Array): unknown {
  const fields = requireDescriptor(typeName);
  const byNumber = new Map(fields.map((field) => [field.number, field]));
  const value: Record<string, unknown> = Object.fromEntries(fields.map((field) => [field.name, defaultValue(field)]));
  let offset = 0;
  while (offset < payload.length) {
    const key = readVarint(payload, offset);
    offset = key.offset;
    const field = byNumber.get(Number(key.value >> 3n));
    const wireType = Number(key.value & 7n);
    if (field === undefined) {
      offset = skipField(payload, offset, wireType);
      continue;
    }
    if (wireType === 2) {
      const length = readVarint(payload, offset);
      const start = length.offset;
      const end = start + Number(length.value);
      if (end > payload.length) throw new Error("Generated Bingo Protobuf field exceeds payload length.");
      const bytes = payload.slice(start, end);
      offset = end;
      if (field.repeated && isVarintKind(field.kind)) {
        let packedOffset = 0;
        while (packedOffset < bytes.length) {
          const item = readVarint(bytes, packedOffset);
          (value[field.name] as unknown[]).push(decodeVarintValue(field.kind, item.value));
          packedOffset = item.offset;
        }
      } else {
        const decoded = field.kind === "string"
          ? textDecoder.decode(bytes)
          : field.kind === "bytes"
            ? bytes
            : decodeMessage(field.kind.slice("message:".length), bytes);
        assignDecoded(value, field, decoded);
      }
      continue;
    }
    if (wireType !== 0 || !isVarintKind(field.kind)) throw new Error("Generated Bingo Protobuf wire type is invalid.");
    const item = readVarint(payload, offset);
    offset = item.offset;
    assignDecoded(value, field, decodeVarintValue(field.kind, item.value));
  }
  const Constructor = (BingoGeneratedMessageConstructors as Partial<Record<string, new (values: never) => unknown>>)[typeName];
  if (Constructor === undefined) throw new Error(`Unknown generated Bingo Protobuf type: ${typeName}`);
  return new Constructor(value as never);
}

function requireDescriptor(typeName: string): readonly BingoFieldDescriptor[] {
  const descriptor = bingoDescriptors[typeName];
  if (descriptor === undefined) throw new Error(`Unknown generated Bingo Protobuf type: ${typeName}`);
  return descriptor;
}

function defaultValue(field: BingoFieldDescriptor): unknown {
  if (field.repeated) return [];
  if (field.optional || field.kind.startsWith("message:")) return null;
  if (field.kind === "string") return "";
  if (field.kind === "bool") return false;
  if (field.kind === "uint64") return "0";
  if (field.kind === "bytes") return new Uint8Array();
  return 0;
}

function assignDecoded(target: Record<string, unknown>, field: BingoFieldDescriptor, decoded: unknown): void {
  if (field.repeated) (target[field.name] as unknown[]).push(decoded);
  else target[field.name] = decoded;
}

function isVarintKind(kind: string): boolean {
  return kind === "int32" || kind === "uint64" || kind === "bool";
}

function isDefaultScalar(kind: string, value: unknown): boolean {
  return (kind === "string" && value === "") || (kind === "bool" && value === false)
    || (kind === "int32" && value === 0) || (kind === "uint64" && (value === "0" || value === 0));
}

function encodeScalarVarint(kind: string, value: unknown): Uint8Array {
  if (kind === "bool") return encodeVarint(value === true ? 1n : 0n);
  if (kind === "int32") return encodeVarint(BigInt.asUintN(64, BigInt(value as number)));
  return encodeVarint(BigInt(value as string | number | bigint));
}

function decodeVarintValue(kind: string, value: bigint): unknown {
  if (kind === "bool") return value !== 0n;
  if (kind === "int32") return Number(BigInt.asIntN(32, value));
  return value.toString();
}

function encodeKey(fieldNumber: number, wireType: number): Uint8Array {
  return encodeVarint(BigInt((fieldNumber << 3) | wireType));
}

function encodeLengthDelimited(payload: Uint8Array): Uint8Array {
  return concatBytes([encodeVarint(BigInt(payload.length)), payload]);
}

function encodeVarint(value: bigint): Uint8Array {
  const bytes: number[] = [];
  let remaining = value;
  do {
    const byte = Number(remaining & 0x7fn);
    remaining >>= 7n;
    bytes.push(remaining === 0n ? byte : byte | 0x80);
  } while (remaining !== 0n);
  return Uint8Array.from(bytes);
}

function readVarint(payload: Uint8Array, start: number): { readonly value: bigint; readonly offset: number } {
  let value = 0n;
  let shift = 0n;
  for (let offset = start; offset < payload.length && offset < start + 10; offset += 1) {
    const byte = payload[offset];
    value |= BigInt(byte & 0x7f) << shift;
    if ((byte & 0x80) === 0) return { value, offset: offset + 1 };
    shift += 7n;
  }
  throw new Error("Generated Bingo Protobuf varint is invalid.");
}

function skipField(payload: Uint8Array, offset: number, wireType: number): number {
  if (wireType === 0) return readVarint(payload, offset).offset;
  if (wireType === 2) {
    const length = readVarint(payload, offset);
    const end = length.offset + Number(length.value);
    if (end > payload.length) throw new Error("Generated Bingo Protobuf field exceeds payload length.");
    return end;
  }
  throw new Error(`Unsupported generated Bingo Protobuf wire type: ${wireType}`);
}

function concatBytes(chunks: readonly Uint8Array[]): Uint8Array {
  const result = new Uint8Array(chunks.reduce((total, chunk) => total + chunk.length, 0));
  let offset = 0;
  for (const chunk of chunks) { result.set(chunk, offset); offset += chunk.length; }
  return result;
}
